### PR TITLE
feat: add docker-compose

### PR DESCRIPTION
**Pull request by itschip**
Adds a simple docker-compose file for development

### CODE REVIEW

**Comment by Siumauricio** [comment]
Thank you for your PR @itschip !

could you add the traefik configuration?

Here is the config 

https://github.com/Dokploy/dokploy/blob/main/server/setup/traefik-setup.ts#L10

**Comment by therumbler** [comment]
great idea! (Docker Compose)

any reason you haven't added dokploy itself to the compose file?

```
  docploy:
    build: .
...
```

**Comment by itschip** [comment]
@therumbler this is mainly meant for setting up requirements for development. Perhaps the file name could be changed to more clearly communicate it?

**Comment by Siumauricio** [comment]
> great idea! (Docker Compose)
> 
> any reason you haven't added dokploy itself to the compose file?
> 
> ```
>   docploy:
>     build: .
> ...
> ```


There is no a specific reasson tbh 😅, it was working for me but is not the ideal way to work, this is really essential when you install the app in a vps but on dev mode no sense

**Comment by itschip** [comment]
@Siumauricio if there isn't anything else you want from me, this PR is ready to go from my side!

**Comment by Siumauricio** [comment]
@itschip Thank you for the PR, i make some adjustments since we don't use docker compose, we use docker swarm so if we use the compose some features will not be available to use in the project you can check here. Also updated how to run the project, i started from scratch (deleted all the files) and everything and it was working without any weird errors/issues and in the new pr you can check the new instructions

Let's move to this PR https://github.com/Dokploy/dokploy/pull/13

**Comment by Siumauricio** [comment]
@itschip Thank you for the PR, i make some adjustments since we don't use docker compose, we use docker swarm so if we use the compose some features will not be available to use in the project you can check here. Also updated how to run the project, i started from scratch (deleted all the files) and everything and it was working without any weird errors/issues and in the new pr you can check the new instructions

Let's move to this PR https://github.com/Dokploy/dokploy/pull/13

**Pull request closed without merging**
