### PR TITLE
feat(notifications): discord decoration toggle

### PR DESCRIPTION
**Pull request by joaotonaco**
A toggle to enable or disable Discord notification embed decorations (Emojis).

### Preview
Settings preview

### With decorations
With decorations

### Without decorations
Without decorations

### CODE REVIEW

**Comment by joaotonaco** [comment]
I kept the emoji in the title when decoration is disabled for easier success/fail visualization

**Comment by kawws** [comment]
Looking good! Much cleaner!

**Review by Siumauricio — COMMENTED** [review]
Thanks!

**Comment by joaotonaco** [comment]
> @joaotonaco can you resolve the conflicts?

Sure!

**Comment by joaotonaco** [comment]
@Siumauricio done!

**Review by thewilloftheshadow — APPROVED** [review]
As much as I like them, I do plan to turn them off for our business instance of Dokploy

**Pull request merged**
