### PR TITLE
i18n settings.json Italian

### PR DESCRIPTION
**Pull request by ipaderi**

### CODE REVIEW

**Review by Siumauricio — CHANGES_REQUESTED** [review]
You are missing some changes, check this PR https://github.com/Dokploy/dokploy/pull/794

**Comment by 190km** [comment]
I think you've got the wrong branch

**Comment by Siumauricio** [comment]
@ipaderi Can you apply this changes?

https://github.com/Dokploy/dokploy/pull/848

I changed the structure to be more easy to integrate new languages

**Comment by Siumauricio** [comment]
Close #863

**Pull request closed without merging**
