### PR TITLE
Fix port input value becoming NaN

### PR DESCRIPTION
**Pull request by AprilNEA**
I have encapsulated a `NumberInput` component to handle string inputs with simple processing of number type fields(eg `port`).

If needed, I can implement the `NumberInput` component in a two-stage approach: during input and upon input completion. This is typically used for handling situations with floats.

## Demo
| Before                                                                 | After                                                                  |
|------------------------------------------------------------------------|------------------------------------------------------------------------|
| Kapture 2024-09-30 at 16 05 42 | Kapture 2024-09-30 at 16 32 41 |

### CODE REVIEW

**Comment by Siumauricio** [comment]
@AprilNEA Hi, thanks for the PR, can you check the validation? for me is not parsing to a number
https://github.com/user-attachments/assets/4106cf41-fa1a-40d0-8033-7ab3de3ef31a

**Comment by AprilNEA** [comment]
> @AprilNEA Hi, thanks for the PR, can you check the validation? for me is not parsing to a number [user-attachments/assets/4106cf41-fa1a-40d0-8033-7ab3de3ef31a](https://github.com/user-attachments/assets/4106cf41-fa1a-40d0-8033-7ab3de3ef31a)

My bad. Now it will finally be converted into a number.

**Comment by b3nab** [comment]
Ehy @AprilNEA we're almost there, could you please run `pnpm run check` to format & lint the files?

**Comment by AprilNEA** [comment]
> Ehy @AprilNEA we're almost there, could you please run `pnpm run check` to format & lint the files?

Sure. I run `pnpm format` and `pnpm run check`, it it all right?
By the way, how do I configure formatter in vscode?

**Comment by b3nab** [comment]
> Sure. I run `pnpm format` and `pnpm run check`, it it all right? 

It looks good now and all checks passed. So just waiting for the final approval.


> By the way, how do I configure formatter in vscode?

You have to configure biome as the formatter for vscode, not prettier. And that's it, it should work then.

**Comment by Siumauricio** [comment]
Thanks!

**Pull request merged**
