### PR TITLE
feat: add update server ip

### PR DESCRIPTION
**Pull request by kdurek**

### CODE REVIEW

**Comment by Siumauricio** [comment]
Can you add a icon button here? to fetch the IP using `getPublicIpWithFallback` function and it will autocomplete the value

so we will have two options

- Using the icon to automatically fill the IP
- Specifying a custom IP

image

**Comment by Siumauricio** [comment]
Also I see you are adding translations for PL, can you add also a new item to appareance page to toggle the language?

**Comment by kdurek** [comment]
Oh thought it was already added by someone who added language package :D
But yeah will be pleased to do this!

**Comment by kdurek** [comment]
@Siumauricio both done!

**Review by Siumauricio — APPROVED** [review]
Thank you!

**Comment by ahmetonurslmz** [comment]
> Can you add a icon button here? to fetch the IP using `getPublicIpWithFallback` function and it will autocomplete the value
> 
> so we will have two options
> 
> * Using the icon to automatically fill the IP
> * Specifying a custom IP
> 
> image

what a great recommendation - loved that!!

**Pull request merged**
