### PR TITLE
refactor(directories): add 600 permissions to SSH_PATH #262

### LINKED ISSUE #262: SSH Keys are not reusable after a Dokploy update
### To Reproduce

1. Create a service
2. Generate a new SSH Key. The key gets saved with permission 600 on `/etc/dokploy/ssh`
3. Apply a Dokploy update
4. Keys under `/etc/dokploy/ssh` has 777, generating this error on deploy:

```
Cloning into '/etc/dokploy/applications/.../code'...
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0777 for '/etc/dokploy/ssh/..._rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
```

### Current vs. Expected behavior

Current: `/etc/dokploy/ssh` has permission 777 on Dokploy update
Expected: `/etc/dokploy/ssh` should keep permission 600

### Provide environment information

```bash
OS: Ubuntu 24.04 LTS
Dokploy: Version: v0.4.0
VPS Provider: Hetzner
```

### Which area(s) are affected? (Select all that apply)

Installation, Application

### Additional context

Related to https://github.com/Dokploy/dokploy/issues/259

https://github.com/Dokploy/dokploy/blob/canary/docker/prod.sh#L60

### PR DESCRIPTION
**Pull request by Siumauricio**
Close #262

### CODE REVIEW

**Comment by lorenzomigliorero** [comment]
@Siumauricio https://github.com/Dokploy/dokploy/blob/canary/docker/prod.sh#L60 will this line override this change?

**Comment by Siumauricio** [comment]
@lorenzomigliorero Not really it will change the permissions only to `SSH_PATH`

Screenshot 2024-07-25 at 1 05 18 AM

**Comment by lorenzomigliorero** [comment]
Cool! Let me test this.

**Comment by Siumauricio** [comment]
Yes @lorenzomigliorero , initially everything will be 777, but once the dokploy server starts it will change to 600.
Screenshot 2024-07-25 at 9 43 10 AM

**Pull request merged**
