### PR TITLE
feat: add swarm overview page

### PR DESCRIPTION
**Pull request by DJKnaeckebrot**
This pull request introduces several new components and updates to the Docker Swarm dashboard, enhancing the user interface and functionality. The most important changes include the addition of a data table for displaying application details, a dialog for showing node configurations, and a monitoring card for an overview of Docker Swarm nodes.

### New Components and Features:

* [`apps/dokploy/components/dashboard/swarm/applications/columns.tsx`](diffhunk://#diff-eaebdfe9858dc5f2ca4a93c69899082a24fec68acb1e560406ad147319b4b169R1-R218): Defined the columns for the application list table, including sorting and cell rendering logic.
* [`apps/dokploy/components/dashboard/swarm/applications/data-table.tsx`](diffhunk://#diff-03e3d9b1df2c7b3363ae00595ec7eab2115899d9ec7cefd486d35b454ecf463dR1-R197): Implemented a reusable `DataTable` component with sorting, filtering, pagination, and column visibility features using `@tanstack/react-table`.
* [`apps/dokploy/components/dashboard/swarm/applications/show-applications.tsx`](diffhunk://#diff-30dca850d6689d4e494768d0122ab6970ba8cbcd0249c45150309c13dc706385R1-R115): Added a component to display detailed information about applications running on a node, combining data from multiple sources.
* [`apps/dokploy/components/dashboard/swarm/details/show-node-config.tsx`](diffhunk://#diff-d51390d69c2e898124fb4d28440b264af865604ebc83a8c4895f042961fb408eR1-R52): Created a dialog component to display the configuration of a node using a code editor for better readability.

### Dashboard Enhancements:

* [`apps/dokploy/components/dashboard/swarm/monitoring-card.tsx`](diffhunk://#diff-ec1b630a17b7569dee2835063bd2f68461f5679107a3cffd39906dd9c320db8cR1-R208): Introduced a monitoring card that provides an overview of Docker Swarm nodes, including total, active, and manager nodes, with tooltips for detailed information.
* [`apps/dokploy/components/dashboard/swarm/details/details-card.tsx`](diffhunk://#diff-a1bbc14de28c16852769f4b1402d6f006427913a48d5cdbb5d91e5a7d5ef6926R1-R132): Updated the node details card to include the new `ShowNodeApplications` and `ShowNodeConfig` components, improving the display of node status and resources.

#### /dashboard/swarm page
image

#### swarm node config button
image

#### swarm node services button
image

#### server show containers button
image

### CODE REVIEW

**Comment by DJKnaeckebrot** [comment]
This should fix/satisfy https://github.com/Dokploy/dokploy/issues/281

**Comment by Siumauricio** [comment]
@DJKnaeckebrot Thanks for this feature!

In this tab I would like to have only this 
image


I think we can replicate the same idea that we have for the main node but for multi server.
image

This way we can have the same component in swarm & server and reuse it for multi servers and the only thing that would change is that in multi server we would use the serverId, to search the information and execute the commands in that server.

Also we should hide the tab when `isCloud` version

**Review by Siumauricio — CHANGES_REQUESTED** [review]
Check

**Comment by DJKnaeckebrot** [comment]
I'll update this today! :)

**Comment by DJKnaeckebrot** [comment]
Hey @Siumauricio,

I have removed the servers part from the swarms page. 

I am not too sure what you have in mind for the servers overview. I have left the components i created in the source so they could be reused. If not let me know and I'll remove them. 

Otherwise I would say lets keep this PR only for the swarms page and track/add servers in a different one.

So this should be ready for review :)

**Review by Siumauricio — APPROVED** [review]
I added support for remote servers :D
Screenshot 2024-12-23 at 12 04 58 AM
Screenshot 2024-12-23 at 12 05 07 AM

**Pull request merged**
