### PR TITLE
feat: add dropdown link

### PR DESCRIPTION
**Pull request by lorenzomigliorero**
image

In case the project has only one domain, the icon will be a simple link.

### CODE REVIEW

**Comment by Siumauricio** [comment]
Looks good, I have this issue when clicking the service name it automatically enter to the project
https://github.com/user-attachments/assets/097bf336-e63e-4c7e-9c11-280bd8fb86df

**Comment by lorenzomigliorero** [comment]
@Siumauricio Fixed

**Comment by Siumauricio** [comment]
@lorenzomigliorero The issue is still happening

**Comment by lorenzomigliorero** [comment]
@Siumauricio forgot to push. should be fine now!

**Pull request merged**
