### PR TITLE
feat: add website translation for zh-Hans

### PR DESCRIPTION
**Pull request by PaiJi**
The PR do:

- [x] Add i18n support by next-intl
- [x] Add zh-Hans translation
- [x] Move en content to en.json
- [x] Add correct language docs link

### CODE REVIEW

**Comment by PaiJi** [comment]
@Siumauricio In the FAQ have same questions, them are q5 and q9:

q5: What type of applications can i deploy with dokploy?
q9: What types of applications can I deploy with Dokploy?

I translated q5 into Chinese as: What types of languages can i deploy with dokploy?
the answers as: We do not restrict programming languages; you are free to choose your preferred language and framework.

**Comment by PaiJi** [comment]
@Siumauricio Are we really sure we are going to say _**If you can’t find what you’re looking for, email our support team and if you’re lucky someone will get back to you.**_?

1. We dont own support team, and you can't find any email address in website.
2. This gives the impression that the project is unreliable.

Advise: Replace them with "Please submit an issue through our GitHub repository or ask questions on our Discord."

**Comment by Siumauricio** [comment]
> @Siumauricio Are we really sure we are going to say _**If you can’t find what you’re looking for, email our support team and if you’re lucky someone will get back to you.**_?
> 
> 1. We dont own support team, and you can't find any email address in website.
> 2. This gives the impression that the project is unreliable.
> 
> Advise: Replace them with "Please submit an issue through our GitHub repository or ask questions on our Discord."

Sounds good the suggestion

**Comment by Siumauricio** [comment]
> Do you think we need a Language Switch Button or just localeDetection base `accept-language` and cookies?

I think we can have both, we can have a language switch button in the footer, and by default automatically detes the accept-language and cookies

**Comment by PaiJi** [comment]
> > Do you think we need a Language Switch Button or just localeDetection base `accept-language` and cookies?
> 
> I think we can have both, we can have a language switch button in the footer, and by default automatically detes the accept-language and cookies

Done.

**Comment by Siumauricio** [comment]
LGTM, can you fix the CI/CD Issues?  https://github.com/Dokploy/dokploy/actions/runs/10734486909/job/29813496960#step:7:17

**Comment by PaiJi** [comment]
> LGTM, can you fix the CI/CD Issues? https://github.com/Dokploy/dokploy/actions/runs/10734486909/job/29813496960#step:7:17

on the way.

**Review by Siumauricio — APPROVED** [review]
Thank you!! <3

**Pull request merged**
