### PR TITLE
feat: add page titles

### PR DESCRIPTION
**Pull request by DJKnaeckebrot**
Adding Titles to the pages.

Format is: 

{pageName} | Dokploy for main and settings pages

Project {projectName} | Dokploy for Projects

Project {projectName} | {appName} | Dokploy for services/applications

Feel free to comment if you agree with the naming "convention" or want sth else :)

### CODE REVIEW

**Comment by mezotv** [comment]
How come you didnt just use nextjs native way of adding title/metadata tags?

**Comment by DJKnaeckebrot** [comment]
@mezotv As far as I am aware that only works for the app router. Dokploy uses the pages router.

**Comment by mezotv** [comment]
> @mezotv As far as I am aware that only works for the app router. Dokploy uses the pages router.

Oh true my bad, they really need to move to the app directory.

**Comment by DJKnaeckebrot** [comment]
@Siumauricio do you have any plans on moving to the app router?

**Comment by kawws** [comment]
Nice detail! Well done!

**Comment by Siumauricio** [comment]
Yes @DJKnaeckebrot, I have plans, I just haven't had time to do the migration, the last time I tried it was a little complicated because there was a dependency that was node-pty that had conflicts with app router at that time, but I think that now it's probably already solved that problem.

**Review by Siumauricio — APPROVED** [review]

**Pull request merged**
