### PR TITLE
fixed modal not closing

### PR DESCRIPTION
**Pull request by shubhankartrivedi**
When adding a Service, the modal wont close automatically so I fixed it.
I also trying to add `router.push` but was not able to do. In future i'll do.

### CODE REVIEW

**Comment by shubhankartrivedi** [comment]
I did some more commits to remove `useRouter` import as it was not used anywhere.

**Comment by mariusihring** [comment]
Wouldn't it be easier to use the DialogTrigger 
Component, that is included inside the Dialog from Shadcn to do this? We should be just able to wrap it around the 'Save' button. This just adds unnecessary state that will become cluttered when there are multiple Dialogs inside the Parent Component. [Shadcn Dialog](https://ui.shadcn.com/docs/components/dialog) [Radix Dialog](https://www.radix-ui.com/primitives/docs/components/dialog)

**Comment by shubhankartrivedi** [comment]
> Wouldn't it be easier to use the DialogTrigger Component, that is included inside the Dialog from Shadcn to do this? We should be just able to wrap it around the 'Save' button. This just adds unnecessary state that will become cluttered when there are multiple Dialogs inside the Parent Component. [Shadcn Dialog](https://ui.shadcn.com/docs/components/dialog) or the docs of the primitive shadcn is using [Radix Dialog](https://www.radix-ui.com/primitives/docs/components/dialog)

Good point! I will do it

**Comment by mariusihring** [comment]
you realise u dont have to close the pr, you can just convert it to a draft or update the files and push again but good luck anyway <3

**Comment by Siumauricio** [comment]
@shubhankartrivedi Would you mind to re-open this PR and try to avoid the use state?  I'm pretty sure we can use something from radix/shadcn that makes the dialog automatically close on submit?

**Comment by shubhankartrivedi** [comment]
> @shubhankartrivedi Would you mind to re-open this PR and try to avoid the use state? I'm pretty sure we can use something from radix/shadcn that makes the dialog automatically close on submit?

I don't have any experience with radix/shadcn. But I have saw that we could use DialogClose thing by them but still it will be bad as it will close the modal even on error and that's bad. 
Also, useState is not that bad.

**Pull request closed without merging**
