### PR TITLE
feat: added Mailserver/ERPNext template

### PR DESCRIPTION
**Pull request by SashaGoncharov19**

### CODE REVIEW

**Comment by SashaGoncharov19** [comment]
@Siumauricio https://github.com/Dokploy/dokploy/issues/408#issuecomment-2355372652
Please advise on how to add some documentation to the template, as previously discussed.

**Comment by seppulcro** [comment]
Hi, just got around to get this working today!
A quick addition, as per the [docker-mailserver docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/security/ssl/#traefik) we need to add an additional container as such
```
whoami:
    image: docker.io/traefik/whoami:latest
    networks:
      - dokploy-network
```
And associate the domain you want to use to that container instead (mail.example.com).

As far as I understood you might also want to edit your traefik config to reflect the required entrypoints:
```
entryPoints:
  mail-smtp:
    address: ':25'
  mail-submission:
    address: ':587'
  mail-submissions:
    address: ':465'
  mail-imap:
    address: ':143'
  mail-imaps:
    address: ':993'
  mail-pop3:
    address: ':110'
  mail-pop3s:
    address: ':995'
  mail-managesieve:
    address: ':4190'
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: letsencrypt
```

**Comment by Eliminationzx** [comment]
have to add DKIM configuration also, you can use command `setup config dkim`.

**Comment by SashaGoncharov19** [comment]
Maybe it will be useful, i created a templates documentation, so you can also help me with it if you wanna.

https://github.com/SashaGoncharov19/dokploy-template-docs
https://sashagoncharov19.github.io/dokploy-template-docs/

**Comment by seppulcro** [comment]
> Hey there!
> 
> Just wanted to bring up something to keep in mind regarding the use of the service behind traefik in this template. It looks like we might need to set up a specific configuration to make sure that traefik can properly direct traffic to the service.
> 
> You can find more information about this at https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/mailserver-behind-proxy/

I think you're right and I did add these to both mailserver compose and traefik config.
I can't end to end test because port 25 is blocked on my box sadly

**Comment by SashaGoncharov19** [comment]
@andrekutianski When I installed this on the Hetzner Robot, there were no problems with traffic, everything was stable and the connections worked fine.

But I also have a home server and there are similar problems. For example, the fact that you need to configure proxying for the mail server to work correctly. 

I have created a separate documentation for this purpose, where we can describe all these points and try to test these settings on our machines before deploying this template.

**Comment by Eliminationzx** [comment]
I'd like to suggest few updates for dms compose.yml file:
```
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    hostname: ${DMS_HOSTNAME}
    ports:
      - 25:25          # SMTP (STARTTLS)
      - 465:465      # SMTP (Implicit TLS)
      - 587:587      # SMTP (STARTTLS)
      - 143:143      # IMAP (STARTTLS)
      - 993:993      # IMAP (Implicit TLS)
      - 110:110      # POP3 (STARTTLS)
      - 995:995      # POP3 (Implicit TLS)
      - 4190:4190  # Managesieve (STARTTLS)
    volumes:
      - dms-mail-data:/var/mail/
      - dms-mail-state:/var/mail-state/
      - dms-mail-logs:/var/log/mail/
      - dms-mail-config:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_FAIL2BAN=${DMS_ENABLE_FAIL2BAN}
      - PERMIT_DOCKER=${DMS_PERMIT_DOCKER}
      - SPOOF_PROTECTION=${DMS_SPOOF_PROTECTION}
      - POSTMASTER_ADDRESS=${DMS_POSTMASTER_ADDRESS}
    cap_add:
      - NET_ADMIN
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: ${DMS_HEALTHCHECK_CMD}
      timeout: ${DMS_HEALTHCHECK_TIMEOUT}
      retries: ${DMS_HEALTHCHECK_RETRIES}
    command: >
      sh -c '
        if [ ! -s /tmp/docker-mailserver/postfix-accounts.cf ]; then
          echo "File does not exist or is empty. Running setup command...";
          setup email add "${DMS_DEFAULT_USER}" "${DMS_DEFAULT_USER_PASS}";
        else
          echo "File exists and is not empty. Skipping setup command.";
        fi
        exec supervisord -c /etc/supervisor/supervisord.conf
      '
    networks:
      - dokploy-network
    labels:
    - traefik.enable=true
    # SMTP
    - traefik.tcp.routers.${HASH}-smtp.rule=HostSNI(`*`)
    - traefik.tcp.routers.${HASH}-smtp.entrypoints=mail-smtp
    - traefik.tcp.routers.${HASH}-smtp.service=${HASH}-smtp
    - traefik.tcp.services.${HASH}-smtp.loadbalancer.server.port=25
    - traefik.tcp.services.${HASH}-smtp.loadbalancer.proxyProtocol.version=1
    # Submission
    - traefik.tcp.routers.${HASH}-submission.rule=HostSNI(`*`)
    - traefik.tcp.routers.${HASH}-submission.entrypoints=mail-submission
    - traefik.tcp.routers.${HASH}-submission.service=${HASH}-submission
    - traefik.tcp.services.${HASH}-submission.loadbalancer.server.port=587
    - traefik.tcp.services.${HASH}-submission.loadbalancer.proxyProtocol.version=1
    # Submissions
    - traefik.tcp.routers.${HASH}-submissions.rule=HostSNI(`*`)
    - traefik.tcp.routers.${HASH}-submissions.entrypoints=mail-submissions
    - traefik.tcp.routers.${HASH}-submissions.service=${HASH}-submissions
    - traefik.tcp.services.${HASH}-submissions.loadbalancer.server.port=465
    - traefik.tcp.services.${HASH}-submissions.loadbalancer.proxyProtocol.version=1
    # IMAP
    - traefik.tcp.routers.${HASH}-imap.rule=HostSNI(`*`)
    - traefik.tcp.routers.${HASH}-imap.entrypoints=mail-imap
    - traefik.tcp.routers.${HASH}-imap.service=${HASH}-imap
    - traefik.tcp.services.${HASH}-imap.loadbalancer.server.port=143
    - traefik.tcp.services.${HASH}-imap.loadbalancer.proxyProtocol.version=1
    # IMAPS
    - traefik.tcp.routers.${HASH}-imaps.rule=HostSNI(`*`)
    - traefik.tcp.routers.${HASH}-imaps.entrypoints=mail-imaps
    - traefik.tcp.routers.${HASH}-imaps.service=${HASH}-imaps
    - traefik.tcp.services.${HASH}-imaps.loadbalancer.server.port=993
    - traefik.tcp.services.${HASH}-imaps.loadbalancer.proxyProtocol.version=1
    # POP3
    - traefik.tcp.routers.${HASH}-pop3.rule=HostSNI(`*`)
    - traefik.tcp.routers.${HASH}-pop3.entrypoints=mail-pop3
    - traefik.tcp.routers.${HASH}-pop3.service=${HASH}-pop3
    - traefik.tcp.services.${HASH}-pop3.loadbalancer.server.port=110
    - traefik.tcp.services.${HASH}-pop3.loadbalancer.proxyProtocol.version=1
    # POP3S
    - traefik.tcp.routers.${HASH}-pop3s.rule=HostSNI(`*`)
    - traefik.tcp.routers.${HASH}-pop3s.entrypoints=mail-pop3s
    - traefik.tcp.routers.${HASH}-pop3s.service=${HASH}-pop3s
    - traefik.tcp.services.${HASH}-pop3s.loadbalancer.server.port=995
    - traefik.tcp.services.${HASH}-pop3s.loadbalancer.proxyProtocol.version=1 
    # Managesieve
    - traefik.tcp.routers.${HASH}-managesieve.rule=HostSNI(`*`)
    - traefik.tcp.routers.${HASH}-managesieve.entrypoints=mail-managesieve
    - traefik.tcp.routers.${HASH}-managesieve.service=${HASH}-managesieve
    - traefik.tcp.services.${HASH}-managesieve.loadbalancer.server.port=4190
    - traefik.tcp.services.${HASH}-managesieve.loadbalancer.proxyProtocol.version=1
  whoami:
    image: docker.io/traefik/whoami:latest
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  dms-mail-data:
  dms-mail-state:
  dms-mail-logs:
  dms-mail-config:
```
And have to add entry points to traefik.
P.S : I've not tested yet, feel free to give feedback.

**Comment by SashaGoncharov19** [comment]
> I'd like to suggest few updates for dms compose.yml file:
> 
> ```
> services:
>   mailserver:
>     image: ghcr.io/docker-mailserver/docker-mailserver:latest
>     hostname: ${DMS_HOSTNAME}
>     ports:
>       - 25:25          # SMTP (STARTTLS)
>       - 465:465      # SMTP (Implicit TLS)
>       - 587:587      # SMTP (STARTTLS)
>       - 143:143      # IMAP (STARTTLS)
>       - 993:993      # IMAP (Implicit TLS)
>       - 110:110      # POP3 (STARTTLS)
>       - 995:995      # POP3 (Implicit TLS)
>       - 4190:4190  # Managesieve (STARTTLS)
>     volumes:
>       - dms-mail-data:/var/mail/
>       - dms-mail-state:/var/mail-state/
>       - dms-mail-logs:/var/log/mail/
>       - dms-mail-config:/tmp/docker-mailserver/
>       - /etc/localtime:/etc/localtime:ro
>     environment:
>       - ENABLE_FAIL2BAN=${DMS_ENABLE_FAIL2BAN}
>       - PERMIT_DOCKER=${DMS_PERMIT_DOCKER}
>       - SPOOF_PROTECTION=${DMS_SPOOF_PROTECTION}
>       - POSTMASTER_ADDRESS=${DMS_POSTMASTER_ADDRESS}
>     cap_add:
>       - NET_ADMIN
>     restart: always
>     stop_grace_period: 1m
>     healthcheck:
>       test: ${DMS_HEALTHCHECK_CMD}
>       timeout: ${DMS_HEALTHCHECK_TIMEOUT}
>       retries: ${DMS_HEALTHCHECK_RETRIES}
>     command: >
>       sh -c '
>         if [ ! -s /tmp/docker-mailserver/postfix-accounts.cf ]; then
>           echo "File does not exist or is empty. Running setup command...";
>           setup email add "${DMS_DEFAULT_USER}" "${DMS_DEFAULT_USER_PASS}";
>         else
>           echo "File exists and is not empty. Skipping setup command.";
>         fi
>         exec supervisord -c /etc/supervisor/supervisord.conf
>       '
>     networks:
>       - dokploy-network
>     labels:
>     - traefik.enable=true
>     # SMTP
>     - traefik.tcp.routers.${HASH}-smtp.rule=HostSNI(`*`)
>     - traefik.tcp.routers.${HASH}-smtp.entrypoints=mail-smtp
>     - traefik.tcp.routers.${HASH}-smtp.service=${HASH}-smtp
>     - traefik.tcp.services.${HASH}-smtp.loadbalancer.server.port=25
>     - traefik.tcp.services.${HASH}-smtp.loadbalancer.proxyProtocol.version=1
>     # Submission
>     - traefik.tcp.routers.${HASH}-submission.rule=HostSNI(`*`)
>     - traefik.tcp.routers.${HASH}-submission.entrypoints=mail-submission
>     - traefik.tcp.routers.${HASH}-submission.service=${HASH}-submission
>     - traefik.tcp.services.${HASH}-submission.loadbalancer.server.port=587
>     - traefik.tcp.services.${HASH}-submission.loadbalancer.proxyProtocol.version=1
>     # Submissions
>     - traefik.tcp.routers.${HASH}-submissions.rule=HostSNI(`*`)
>     - traefik.tcp.routers.${HASH}-submissions.entrypoints=mail-submissions
>     - traefik.tcp.routers.${HASH}-submissions.service=${HASH}-submissions
>     - traefik.tcp.services.${HASH}-submissions.loadbalancer.server.port=465
>     - traefik.tcp.services.${HASH}-submissions.loadbalancer.proxyProtocol.version=1
>     # IMAP
>     - traefik.tcp.routers.${HASH}-imap.rule=HostSNI(`*`)
>     - traefik.tcp.routers.${HASH}-imap.entrypoints=mail-imap
>     - traefik.tcp.routers.${HASH}-imap.service=${HASH}-imap
>     - traefik.tcp.services.${HASH}-imap.loadbalancer.server.port=143
>     - traefik.tcp.services.${HASH}-imap.loadbalancer.proxyProtocol.version=1
>     # IMAPS
>     - traefik.tcp.routers.${HASH}-imaps.rule=HostSNI(`*`)
>     - traefik.tcp.routers.${HASH}-imaps.entrypoints=mail-imaps
>     - traefik.tcp.routers.${HASH}-imaps.service=${HASH}-imaps
>     - traefik.tcp.services.${HASH}-imaps.loadbalancer.server.port=993
>     - traefik.tcp.services.${HASH}-imaps.loadbalancer.proxyProtocol.version=1
>     # POP3
>     - traefik.tcp.routers.${HASH}-pop3.rule=HostSNI(`*`)
>     - traefik.tcp.routers.${HASH}-pop3.entrypoints=mail-pop3
>     - traefik.tcp.routers.${HASH}-pop3.service=${HASH}-pop3
>     - traefik.tcp.services.${HASH}-pop3.loadbalancer.server.port=110
>     - traefik.tcp.services.${HASH}-pop3.loadbalancer.proxyProtocol.version=1
>     # POP3S
>     - traefik.tcp.routers.${HASH}-pop3s.rule=HostSNI(`*`)
>     - traefik.tcp.routers.${HASH}-pop3s.entrypoints=mail-pop3s
>     - traefik.tcp.routers.${HASH}-pop3s.service=${HASH}-pop3s
>     - traefik.tcp.services.${HASH}-pop3s.loadbalancer.server.port=995
>     - traefik.tcp.services.${HASH}-pop3s.loadbalancer.proxyProtocol.version=1 
>     # Managesieve
>     - traefik.tcp.routers.${HASH}-managesieve.rule=HostSNI(`*`)
>     - traefik.tcp.routers.${HASH}-managesieve.entrypoints=mail-managesieve
>     - traefik.tcp.routers.${HASH}-managesieve.service=${HASH}-managesieve
>     - traefik.tcp.services.${HASH}-managesieve.loadbalancer.server.port=4190
>     - traefik.tcp.services.${HASH}-managesieve.loadbalancer.proxyProtocol.version=1
>   whoami:
>     image: docker.io/traefik/whoami:latest
>     networks:
>       - dokploy-network
> 
> networks:
>   dokploy-network:
>     external: true
> 
> volumes:
>   dms-mail-data:
>   dms-mail-state:
>   dms-mail-logs:
>   dms-mail-config:
> ```
> 
> And have to add entry points to traefik. P.S : I've not tested yet, feel free to give feedback.

Will check it today on my home server, thanks!

**Comment by Siumauricio** [comment]
Hi, Running the instance of erpnext there is some issue probably in some container I got this error
image
image

**Comment by ShubashBiswas** [comment]
> Hi, Running the instance of erpnext there is some issue probably in some container I got this error image image

You should wait till create-site-1 container is stopped

**Comment by Siumauricio** [comment]
@SashaGoncharov19 The thing is i waited around 30 mins to see if something changed, but nothing changes at the end

**Comment by ShubashBiswas** [comment]
Umm that's strange I was successfully running ERPNext every time during rebuilt or clean install.

**Comment by SashaGoncharov19** [comment]
So, I want to tell about the settings of the mail server. It's very cool that we want to make everything work out of the box on all servers, but it doesn't work that way. I've tried different mail servers, different settings, and tried a lot of options. Each server has its own settings. If you install it on Hetzner, for the most part, the basic settings are enough. If you install it on your home server, the settings are more complicated, you need to proxy requests, there are different configurations, and so on. It all depends on how the network is configured on the server.

I think it would be best to just make documentation on how to deploy a mail server, because it will be a big headache to maintain it all. Someone will constantly open an issue and ask why it doesn't work if they don't understand how to operate Linux systems, Traefik or something else.

Stalwart mail server has documentation on how to deploy their server under Traefik proxy. We can use this and create a template from it, and describe the documentation on how to set up Traefik that works with Dokploy.

If you have any alternative solutions or questions, please do not hesitate to contact me, I would love to hear them as well.

**Comment by ShubashBiswas** [comment]
@SashaGoncharov19 

I have also tried several apps for email server settings for the same. After trying those I can suggest 2 of them for template. 

> 1. Stalwart Mail Server
> 2. Docker Mail Server

I am running a Docker mail Server without Traefik config, Even multiple domains are configured. The main disadvantage of Docker Mail Server is webui/dashboard. 

A stalwart mail server is preferable and easy to deploy but needs to be configured properly (Traefik and stalwart mail server configs). I am still trying to understand the proper configuration for the stalwart mail server.

I will keep you posted about it.

**Comment by SashaGoncharov19** [comment]
@ShubashBiswas 

Also. I'm currently using Docker Mailserver on Hetzner and it works great with the basic configuration.

**Review by ShubashBiswas — CHANGES_REQUESTED** [review]
I am suggesting the changes below
1. image: frappe/erpnext:v15.35.1 to erpnext:latest
2. mariadb:11.4
3. redis:7.4-alpine

**Comment by iraunit** [comment]
Waiting for the Email Server template to be added in Dokploy. 
I'm just writing to support you.

**Comment by Siumauricio** [comment]
> So I want to talk about the mail server settings. It's very cool that we want everything to work out of the box on all servers, but it doesn't work that way. I've tried different mail servers, different settings, a lot of options. Every server has its own settings. If you install it at Hetzner, the default settings are usually sufficient. If you install it on your home server, the settings are more complicated, you have to proxy requests, there are different configurations and so on. It all depends on how the network is configured on the server.
> 
> I think it would be best to just make documentation on how to set up a mail server, because it will be a big headache to maintain it all. Someone will always open an issue and ask why it doesn't work if they don't understand how to use Linux systems, Traefik or whatever.
> 
> Stalwart Mail Server has documentation on how to use their server with Traefik Proxy. We can use this and create a template from it and describe the documentation on how to set up Traefik to work with Dokploy.
> 
> If you have any alternative solutions or questions, please do not hesitate to contact me, I would love to hear them as well.

Makes sense tbh, can you add a explanation in the docs how to setup this and the things you need to take in consideration before you create this template?

**Comment by ShubashBiswas** [comment]
https://sashagoncharov19.github.io/dokploy-template-docs/mail-server

**Comment by Siumauricio** [comment]
> https://sashagoncharov19.github.io/dokploy-template-docs/mail-server

Yeah but ideally should be in the dokploy docs

**Comment by SashaGoncharov19** [comment]
Mailserver will be released after some dokploy architecture changes.

**Comment by Siumauricio** [comment]
After 30 mins the containers is showing the same installing frappe....
image


image

**Comment by SashaGoncharov19** [comment]
https://github.com/Dokploy/website/pull/2

**Pull request merged**
