### PR TITLE
feat(i18n): add support for german

### PR DESCRIPTION
**Pull request by mezotv**
Adds support for the german language.

### CODE REVIEW

**Comment by mezotv** [comment]
Why are the lints failing from files I didnt even touch?

**Comment by Siumauricio** [comment]
pull the latest changes from canary

**Comment by mezotv** [comment]
> And one more thing please rember open a new branch and merge new branch to canary. or it will be like this:
> your contribution willn't count.

Thats not how github works, of course it will count.

**Comment by mezotv** [comment]
> pull the latest changes from canary

Github wouldnt let me do that earlier due to the merge conficts that were added by your other pr.

**Comment by PaiJi** [comment]
> > And one more thing please rember open a new branch and merge new branch to canary. or it will be like this:
> > your contribution willn't count.
> 
> Thats not how github works, of course it will count.

You are right🤔. i got the conditions wrong for that situation to occur.

**Comment by Siumauricio** [comment]
@mezotv what do you mean?

You can pull the changes from canary and resolve the conflicts manually

**Comment by mezotv** [comment]
> @mezotv what do you mean?
> 
> You can pull the changes from canary and resolve the conflicts manually

Yea I know but the conflicts seem so major I cant fix them in the online editor.

**Comment by Siumauricio** [comment]
😅 you need to fix in your code editor..

**Pull request closed without merging**
