### PR TITLE
feat(logs): multi select fiter logs & hide/show timestamp

### PR DESCRIPTION
**Pull request by 190km**
# Multi select

{F52C90D1-018F-4143-B583-7E457AB0AA64}
{E0A5D734-0B18-4575-8A69-C117B7E8F4F8}

# Hide/Show timestamp
{10146BCE-5D88-409A-83CB-95DEAD35F4A4}
image

### CODE REVIEW

**Comment by PiyushDixit96** [comment]
looks cool.
can you add option to hide date time too?

**Comment by 190km** [comment]
hey @PiyushDixit96, done.

**Review by drudge — APPROVED** [review]
Love it

**Comment by drudge** [comment]
image

**Comment by 190km** [comment]
{306AD8D8-C98A-40DC-8147-976E0CDE0C60}
{FEC7B760-C01E-4B64-81AB-A09EB6B08C5A}

**Pull request merged**
