### PR TITLE
feat: add preview deployments #379

### PR DESCRIPTION
**Pull request by Siumauricio**
To test it:

```bash
curl -sSL https://dokploy.com/feature.sh | sh
```

### CODE REVIEW

**Comment by Santaantjuh** [comment]
Hi! I have been playing around with it for a bit, a few things that might be nice:
1. Disabling Autodeploy also won't create any preview deployments. It would be nice if it could still make preview deployments if auto-deploy is disabled.
2. The domain is incredibly long. Coolify has a setting where you can change it, it would be nice if you could have just an id, for example, uysrjp-bfuslc.domain.example, without the entire preview-app-name. It would also be nice if you could for instance use the pr-id.

Thank you!

**Comment by TheOnlyWayUp** [comment]
It'd be nice if it was the PR id, yeah. Some sort of templating syntax would be helpful as cloudflare doesn't protect multi-level subdomains for free.

Ie, for a site behind cloudflare,
`https://21.wpd.rambhat.la`
is invalid and causes an SSL Error that can only be fixed by upgrading your CF Account, or disabling CF's Proxy for `*.wpd.rambhat.la`.

What would be great is templating syntax like:
```
https://${template_id}-wpd.rambhat.la
```
which would become `21-wpd.rambhat.la`, protected by CF as it's a single level subdomain.

**Comment by Siumauricio** [comment]
> It'd be nice if it was the PR id, yeah. Some sort of templating syntax would be helpful as cloudflare doesn't protect multi-level subdomains for free.
> 
> Ie, for a site behind cloudflare, `https://21.wpd.rambhat.la` is invalid and causes an SSL Error that can only be fixed by upgrading your CF Account, or disabling CF's Proxy for `*.wpd.rambhat.la`.
> 
> What would be great is templating syntax like:
> 
> ```
> https://${template_id}-wpd.rambhat.la
> ```
> 
> which would become `21-wpd.rambhat.la`, protected by CF as it's a single level subdomain.

We don't generate subdomains levels, we only create domains base on the project name so for example so everytime becomes as 


project-name-appname-preview.{your-domain}

**Comment by Siumauricio** [comment]
> Hi! I have been playing around with it for a bit, a few things that might be nice:
> 
> 1. Disabling Autodeploy also won't create any preview deployments. It would be nice if it could still make preview deployments if auto-deploy is disabled.
> 2. The domain is incredibly long. Coolify has a setting where you can change it, it would be nice if you could have just an id, for example, uysrjp-bfuslc.domain.example, without the entire preview-app-name. It would also be nice if you could for instance use the pr-id.
> 
> Thank you!

I like the idea to use the pr-id as domain 👍

**Pull request merged**
