### PR TITLE
feat: New Templates

### PR DESCRIPTION
**Pull request by DrMxrcy**
Peppermint Template
Windmill Template
ActivePieces Template
InvoiceShelf Template
Postiz Template
Slash Template
Discord Tickets Template

### CODE REVIEW

**Comment by DrMxrcy** [comment]
Added 2 more templates while pending review.

**Comment by Siumauricio** [comment]
Hey thank you for the templates, appreciated!

I'm getting this error for windmill, I'm deploying to a server remote
Screenshot 2024-11-12 at 11 01 05 PM

The activepieces is restarting forever and the domain is not being accesible
Screenshot 2024-11-12 at 11 01 49 PM


The linkstack template domain is not working

**Comment by DrMxrcy** [comment]
> Hey thank you for the templates, appreciated!
> 
> I'm getting this error for windmill, I'm deploying to a server remote Screenshot 2024-11-12 at 11 01 05 PM
> 
> The activepieces is restarting forever and the domain is not being accesible Screenshot 2024-11-12 at 11 01 49 PM
> 
> The linkstack template domain is not working
> 
> the chatwoot template by some reason is redirecting to https 🤔 and is not being accessible to the application
> 
> the discord tickets is throwing this error Screenshot 2024-11-12 at 11 20 55 PM

Hello! I will go an retest! In terms of Discord Tickets, user ENV Variables are needed!

**Comment by DrMxrcy** [comment]
@Siumauricio 

- Fixed Windmill
- Removed Linkstack due to traefik issues (From thier Repo Issues)
- Discord Tickets has User Fillable ENVs for the Error 

These are not working in my Dev Setup, but I think they are if you can give them a new try

- Chatwoot
- Active Pieces

**Comment by Siumauricio** [comment]
@DrMxrcy 

Windmill is working ✅
ActievePieces is working ✅

Chatwoot by some reason have more than 15 minutes deploying, something is wrong maybe
Screenshot 2024-11-17 at 9 40 24 AM

**Comment by DrMxrcy** [comment]
> @DrMxrcy
> 
> Windmill is working ✅ ActievePieces is working ✅
> 
> Chatwoot by some reason have more than 15 minutes deploying, something is wrong maybe Screenshot 2024-11-17 at 9 40 24 AM

Removed Chatwoot Template for this PR!

**Review by Siumauricio — APPROVED** [review]
Thanks!

**Pull request merged**
